export const zines = [
  {
    id: '1',
    title: 'The Whispering Woods',
    author: 'Elara Meadows',
    coverImage: 'https://placehold.co/400x600',
    aiHint: 'forest illustration',
    description: 'An illustrated journey through a mythical forest.',
  },
  {
    id: '2',
    title: 'Echoes of the City',
    author: 'Kaelen Vance',
    coverImage: 'https://placehold.co/400x600',
    aiHint: 'cityscape painting',
    description: 'A collection of short stories about urban life.',
  },
  {
    id: '3',
    title: 'Digital Dreams',
    author: 'Cyra Vector',
    coverImage: 'https://placehold.co/400x600',
    aiHint: 'abstract digital art',
    description: 'Exploring the intersection of technology and art.',
  },
  {
    id: '4',
    title: 'Transient Closures',
    author: 'Rowan Field',
    coverImage: 'https://placehold.co/400x600',
    aiHint: 'minimalist landscape',
    description: 'Poetry on the themes of loss and acceptance.',
  },
  {
    id: '5',
    title: 'Urban Canvas',
    author: 'Graffito',
    coverImage: 'https://placehold.co/400x600',
    aiHint: 'street art',
    description: 'A photo series on vibrant street art from around the world.',
  },
  {
    id: '6',
    title: 'Cosmic Chronicles',
    author: 'Orion Sky',
    coverImage: 'https://placehold.co/400x600',
    aiHint: 'galaxy illustration',
    description: 'Sci-fi tales from the edge of the universe.',
  },
  {
    id: '7',
    title: 'The Silent Observer',
    author: 'Jane Doe',
    coverImage: 'https://placehold.co/400x600',
    aiHint: 'person watching',
    description: 'A noir mystery set in a rain-soaked city.',
  },
  {
    id: '8',
    title: 'Byte-Sized Poems',
    author: 'Ada Lovelace',
    coverImage: 'https://placehold.co/400x600',
    aiHint: 'computer code',
    description: 'Poetry generated by an AI, exploring themes of consciousness.',
  }
];

export const featuredZines = zines.slice(0, 3);
export const trendingZines = zines.slice(2, 8);
export const fictionZines = [zines[1], zines[5], zines[6], ...zines.slice(0,3)];
export const poetryZines = [zines[3], zines[7], ...zines.slice(2,6)];
export const techZines = [zines[2], zines[7], ...zines.slice(4,8)];

export const categories = [
  {
    name: 'Art',
    zineCount: 23,
    description: 'A canvas for visual creativity and design.',
  },
  {
    name: 'Fiction',
    zineCount: 18,
    description: 'Journals and photos from around the world.',
  },
  {
    name: 'Poetry',
    zineCount: 12,
    description: 'Collections of verses and prose.',
  },
  {
    name: 'Tech',
    zineCount: 8,
    description: 'Exploring the intersection of technology and art.',
  },
];
